In [2]:
import pandas as pd

In [3]:
ref_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Multipath/multipath_data_test.csv",header=None)
ref_ref_data['Label'] = 1
ref_ref_data.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,Label
0,3.895949,1.041301,1.451234,-1.870216,-4.416225,0.120368,1.263571,-1.980865,0.544944,0.478177,...,0.149843,1.910252,0.875001,0.084611,1.816088,-1.682748,-1.011242,0.697825,-0.937922,1
1,-0.948959,0.213329,0.977819,-0.663076,0.540329,0.741871,3.304675,-1.016243,-0.962062,0.130710,...,-1.412426,0.304016,-2.275173,0.059073,0.217074,0.320389,-1.236983,-2.069800,-0.478530,1
2,-0.486374,-0.241272,-2.682882,0.468271,-1.156260,-2.199973,2.871217,-2.372573,-1.713838,0.764716,...,2.426290,-0.449349,1.253130,0.540717,0.249505,0.289251,-1.969165,1.819213,-3.962357,1
3,-0.312561,-0.481646,0.226875,-4.679536,-0.606569,0.571430,3.255990,-1.084721,1.206331,2.096823,...,-1.795280,1.231726,-1.987034,-0.310971,1.180060,3.015395,0.770656,-1.413331,0.799290,1
4,-1.674838,-0.608310,2.012779,-0.648921,-1.792660,-3.290794,2.732783,-0.826441,-3.582865,2.392318,...,-0.730917,-0.478840,1.843346,1.731042,-0.263574,-0.882737,0.148261,-0.455160,-0.415569,1

In [4]:
ref_ref_data.loc[10000:,'Label'] = 0

In [13]:
non_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Multipath/channel_3_multipath_data_non_ref_ref.csv",header=None)
non_ref_data['Label'] = 0
non_ref_data.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,Label
0,1.181828,-0.103814,-1.830222,2.142044,-1.367635,-1.434712,-1.594116,0.821215,0.390048,-1.617316,...,1.652689,-0.312044,-1.783078,-0.545015,0.178581,-0.411137,0.889101,-0.344036,-0.102738,0
1,0.072744,-0.498591,-2.233785,-1.166063,-2.080267,1.626412,-0.218130,0.457252,1.746959,-1.619308,...,0.931833,-0.727636,1.490228,0.547797,-0.445581,-0.891944,-0.811993,-0.345474,-0.544833,0
2,-0.775882,-1.348131,1.635620,1.615780,-2.399878,1.289463,1.342190,0.246017,-1.343657,1.495023,...,1.204663,-0.713091,-3.134738,-0.583504,-2.484158,1.815052,0.787034,0.811779,0.133024,0
3,0.426477,2.187286,1.922735,0.167498,0.466763,2.656741,-2.070113,-1.531735,-0.268769,2.168658,...,-0.547625,-0.282270,-1.589055,-0.001606,-0.418594,-0.870904,-0.796093,1.472178,-0.011454,0
4,1.130784,-0.225079,-1.698315,0.716967,0.684028,-0.096237,0.453348,0.136393,0.726360,-0.389570,...,2.385063,1.364032,-1.105691,-0.601228,-1.428802,0.274901,-0.291492,0.188488,1.015626,0

In [14]:
multipath_dataset = ref_ref_data.append(non_ref_data, ignore_index = True)

In [15]:
print(len(multipath_dataset))

520000

In [5]:
ref_ref_data.to_csv('/Users/niall/Documents/Cypress_Code/Data/Multipath/multi_test_one.csv')