In [2]:
import pandas as pd

In [3]:
ref_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Sub_data/AWGN/noise_ref_ref_data_awgn.csv",header=None)
ref_ref_data['Label'] = 1
ref_ref_data.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,Label
0,1.051561,-1.812413,-1.282181,-1.537379,-1.312746,0.630741,-0.755540,-1.166698,1.312990,-0.754799,...,0.758688,0.646169,-0.544777,0.898727,0.917320,0.419724,-1.064099,0.944799,-0.897874,1
1,1.315440,-1.094232,-1.170096,-0.570338,-0.553016,1.321477,-1.141318,-1.292361,0.987489,-1.049869,...,0.848366,1.092143,-1.682454,1.493133,0.964291,1.331322,-0.594714,0.780146,-0.705422,1
2,1.158727,-0.574593,-0.905085,-0.834252,-1.088100,1.055353,-1.283483,-0.752392,1.332655,-1.079839,...,0.233013,1.263450,-1.006359,1.582038,1.420646,0.869384,-0.881005,1.298919,-0.224433,1
3,0.838787,-0.579121,-0.519992,-1.300486,-0.851300,0.419019,-1.254187,-1.406267,1.151718,-0.532881,...,0.739051,1.662349,-1.071852,0.904596,1.482208,1.035863,-0.974579,0.792549,-0.700056,1
4,1.135381,-1.075502,-0.714762,-0.732275,-0.876236,1.555253,-0.690136,-0.860484,0.750607,-0.750287,...,1.086042,1.390592,-1.207494,1.140487,1.130769,1.419540,-0.743628,1.310908,-0.653133,1

In [4]:
non_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Sub_data/AWGN/noise_non_ref_data_awgn.csv",header=None)
non_ref_data['Label'] = 0
non_ref_data.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,Label
0,-0.547143,1.381689,-1.175398,1.510019,-0.613112,-1.033156,-0.645331,-1.220808,1.328798,-0.969381,...,-0.498960,-0.639837,-1.232235,1.438112,1.313282,-0.747041,1.460791,1.251484,0.815387,0
1,0.921544,1.728173,1.134166,-0.837843,-0.241139,-1.345884,0.518831,1.235211,-0.909178,1.219555,...,-1.035351,1.817887,-1.190921,1.237264,0.454439,-1.584369,-1.096204,1.099253,1.951755,0
2,-1.355108,-0.473240,-1.264296,0.898478,1.211024,-1.194479,0.988045,1.291264,1.170803,-1.335797,...,0.773544,1.213564,-0.597468,-0.460068,1.592401,0.918374,0.835765,0.465751,1.246937,0
3,-1.018479,1.232433,-1.080822,1.077336,1.260404,-1.055363,-0.671844,0.920700,0.874328,0.203234,...,1.163478,-0.780608,1.044615,-0.980117,-1.028404,-0.978363,-0.897255,0.726961,-0.960593,0
4,-1.112396,1.072621,0.789139,0.712148,1.471964,1.280398,-0.870501,-0.883954,-1.508521,1.086672,...,-0.928977,0.998576,-0.919710,-1.007034,1.128341,-1.483114,1.197118,0.539215,-1.527021,0

In [5]:
awgn_dataset = ref_ref_data.append(non_ref_data, ignore_index = True)

In [6]:
print(len(awgn_dataset))

300000

In [ ]:
awgn_dataset.to_csv('awgn_dataset.csv')

##Â All Data

In [34]:
noiseless_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/AWGN/noise_data_awgn_snrten.csv",header=None)
noiseless_data['Label'] = 1

In [35]:
noiseless_data.loc[100000:,'Label'] = 0

In [36]:
noiseless_data.tail()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,Label
299995,0.720321,-1.280824,1.750980,0.751537,-0.973152,0.681530,-0.697934,-1.006807,1.168284,-1.235736,...,-1.354171,-1.431044,1.640805,-1.085975,1.154897,0.663347,-0.923178,1.603021,-1.082419,0
299996,-0.863983,-1.125012,-1.161161,1.133716,-1.298446,-1.061574,1.574201,0.744906,0.658212,0.273171,...,1.285214,0.954037,-1.829276,1.092770,0.569743,-0.312412,-1.272070,-1.258073,-0.634973,0
299997,1.617404,-1.299594,0.701829,-0.873638,-0.677513,0.844617,0.941629,-1.019205,1.165948,0.978499,...,-0.946560,0.855754,1.494776,1.159985,-0.654907,-1.002579,-1.129797,-1.028790,1.233853,0
299998,0.930689,0.721226,-1.726965,-1.045488,1.119838,1.216376,-0.609093,-0.773889,1.194127,0.869388,...,-0.998344,-0.715161,0.575574,1.694579,-1.290217,-1.628775,1.255036,0.986704,-0.922289,0
299999,1.435374,0.989281,0.998530,-0.686329,-0.951250,1.308931,1.358263,-1.463725,-1.027441,1.549772,...,1.133301,-1.125555,-0.472208,1.190111,0.998459,-0.842604,-1.342584,1.036922,0.723650,0

In [37]:
print(noiseless_data[99998:100005])

               0         1         2         3         4         5         6  \
99998  -1.326511  1.085976  1.135610  1.488953  1.377423  1.242107 -1.798333
99999   1.284248 -1.273882 -0.747079  1.118671 -1.052989  0.867392  1.052843
100000 -0.710546 -1.499923 -1.093196 -0.836169  1.262766 -1.117570  1.164703
100001 -1.678697  1.189523 -1.018826  1.445096 -0.940376  1.343219 -1.245567
100002  0.801614  0.662931  0.909995  0.807340  1.095909  0.420960  1.418939
100003 -1.518751  0.437045  1.069605  0.970522  0.874088  1.077348  1.106216
100004 -0.893277 -1.019302  1.294002  1.338884 -1.012477  0.951310 -0.760574

               7         8         9  ...        22        23        24  \
99998  -1.231717 -1.486034  0.475319  ... -0.845059  1.380928 -1.104525
99999  -0.712774 -0.770420  0.989880  ...  0.719702 -1.222573  1.194706
100000 -1.444392  1.139688  1.261395  ... -1.333511 -0.743386  1.374406
100001  0.989554 -1.232293  1.399921  ... -1.308732  1.049395 -1.585885
100002  1.309323  0.912566  1.003531  ...  0.418125  1.463152  0.469416
100003  0.956076  0.805247  0.598075  ...  0.884765  1.535559  0.828006
100004 -1.067733 -1.383204  0.857025  ... -1.049021  1.132198  1.156999

              25        26        27        28        29        30  Label
99998  -0.435116  0.933513 -1.443245  1.136926  1.320150 -1.543708      1
99999  -0.500934  0.934163 -1.155349 -0.933276 -0.815003 -1.219560      1
100000  1.399174 -0.599540  1.072713 -0.952594 -1.276041  0.905370      0
100001  0.971601 -0.967754  0.884561 -0.838384  0.935172 -0.898914      0
100002  0.666837  1.474636  1.062427  1.064704  1.281254  1.448036      0
100003  1.358413  1.086042  1.139028  1.118505  0.748303  1.398009      0
100004 -0.452684  1.637191 -1.192434 -1.230910 -0.736300  0.677445      0

[7 rows x 32 columns]

In [38]:
print(len(noiseless_data))

300000

In [39]:
noiseless_data.to_csv('/Users/niall/Documents/Cypress_Code/Data/AWGN/noise_data_awgn_snrten_final.csv')

# Large Data

In [ ]:
ref_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Sub_data/AWGN/noise_ref_ref_data_awgn.csv",header=None)
ref_ref_data['Label'] = 1
ref_ref_data.head()

In [ ]:
non_ref_data = pd.read_csv("/Users/niall/Documents/Cypress_Code/Data/Sub_data/AWGN/noise_non_ref_data_awgn.csv",header=None)
non_ref_data['Label'] = 0
non_ref_data.head()

In [ ]:
awgn_dataset = ref_ref_data.append(non_ref_data, ignore_index = True)

In [ ]:
print(len(awgn_dataset))

In [ ]:
awgn_dataset.to_csv('/Users/niall/Documents/Cypress_Code/Data/AWGN/noise_data_awgn_snrten_final_large.csv')